import { PERMISSION_CATALOG, PERMISSIONS } from "./permissions";
export { PERMISSION_CATALOG, PERMISSIONS } from "./permissions";
export type { PermissionDef, PermissionName } from "./permissions";

export const ROLES = [
  "super_admin",
  "admin",
  "project_manager",
  "marketing_manager",
  "content_editor",
  "developer",
] as const;

export type Role = (typeof ROLES)[number];

/** Highest to lowest privilege, used for RBAC checks. */
export const ROLE_LEVEL: Record<Role, number> = {
  super_admin: 5,
  admin: 4,
  project_manager: 3,
  marketing_manager: 2,
  content_editor: 1,
  developer: 0,
};

export const ROLE_LABELS: Record<Role, string> = {
  super_admin: "Super Admin",
  admin: "Admin",
  project_manager: "Project Manager",
  marketing_manager: "Marketing Manager",
  content_editor: "Content Editor",
  developer: "Developer",
};

/** Built-in permission map per system role. `super_admin` bypasses checks. */
export const ROLE_PERMISSIONS: Record<string, string[]> = {
  super_admin: [...PERMISSIONS],
  admin: [...PERMISSIONS],
  project_manager: [
    "dashboard:view",
    "analytics:view",
    "leads:view",
    "leads:create",
    "leads:update",
    "leads:delete",
    "leads:assign",
    "leads:export",
    "contacts:view",
    "contacts:update",
    "contacts:reply",
    "contacts:delete",
    "estimates:view",
    "estimates:update",
    "estimates:delete",
    "services:view",
    "services:create",
    "services:update",
    "services:delete",
    "portfolio:view",
    "portfolio:create",
    "portfolio:update",
    "portfolio:delete",
    "team:view",
    "team:create",
    "team:update",
    "team:delete",
    "testimonials:view",
    "testimonials:create",
    "testimonials:update",
    "testimonials:delete",
    "faqs:view",
    "faqs:create",
    "faqs:update",
    "faqs:delete",
    "blogs:view",
    "blogs:create",
    "blogs:update",
    "blogs:delete",
    "blogs:publish",
    "careers:view",
    "careers:create",
    "careers:update",
    "careers:delete",
    "applications:view",
    "applications:update",
    "applications:delete",
    "subscribers:view",
    "media:view",
    "media:upload",
    "media:delete",
    "tasks:view",
    "tasks:view_all",
    "tasks:create",
    "tasks:update",
    "tasks:delete",
    "tasks:verify",
    "attendance:view",
    "attendance:view_all",
    "payroll:view",
    "payments:view",
    "payments:view_details",
    "payments:create",
    "payments:link_create",
    "payments:send_whatsapp",
    "payments:resend_whatsapp",
    "agreements:view",
    "agreements:create",
    "agreements:update",
    "agreements:delete",
    "agreements:sign_link",
    "agreements:download",
  ],
  marketing_manager: [
    "dashboard:view",
    "analytics:view",
    "leads:view",
    "leads:update",
    "contacts:view",
    "contacts:reply",
    "services:view",
    "portfolio:view",
    "testimonials:view",
    "testimonials:create",
    "testimonials:update",
    "faqs:view",
    "faqs:create",
    "faqs:update",
    "blogs:view",
    "blogs:create",
    "blogs:update",
    "blogs:publish",
    "subscribers:view",
    "media:view",
    "media:upload",
    "seo:manage",
  ],
  content_editor: [
    "dashboard:view",
    "analytics:view",
    "leads:view",
    "services:view",
    "services:create",
    "services:update",
    "portfolio:view",
    "portfolio:create",
    "portfolio:update",
    "team:view",
    "team:create",
    "team:update",
    "testimonials:view",
    "testimonials:create",
    "testimonials:update",
    "faqs:view",
    "faqs:create",
    "faqs:update",
    "blogs:view",
    "blogs:create",
    "blogs:update",
    "subscribers:view",
  ],
  developer: [
    "tasks:view",
    "tasks:submit",
    "attendance:view",
    "payroll:view",
    "media:upload",
  ],
};

export const PORTFOLIO_STATUS = ["draft", "published", "hidden"] as const;

export const LEAD_STATUS = ["new", "contacted", "in_progress", "quoted", "won", "lost"] as const;

export type LeadStatus = (typeof LEAD_STATUS)[number];
